In [2]:
# ── Reproducibility Header ────────────────────────────────────────────

import sys, random
import numpy as np
import warnings

RANDOM_SEED = 414  # Course constant. Do not change.
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
warnings.filterwarnings('ignore', category=FutureWarning)

# Environment check
print(f'Python  : {sys.version.split()[0]}')
print(f'NumPy   : {np.__version__}')
print(f'Seed    : {RANDOM_SEED}')

Python  : 3.11.2
NumPy   : 2.4.3
Seed    : 414

In [5]:
import fastf1
import pandas as pd

# Load a complete session from the 2024 Bahrain Grand Prix Qualifying
session = fastf1.get_session(2024, 'Monzo', 'Q')
session.load()

df_info = pd.DataFrame({
    "field": [
        "session_name",
        "event_name",
        "num_laps_in_results",
        "results_columns",
        "laps_head"
    ],
    "Information": [
        session.name,
        session.event['EventName'],
        session.results.shape[0],
        list(session.results.columns),
        session.laps.head().to_dict()
    ]
})

display(df_info)

events      WARNING 	Correcting user input 'Monzo' to 'Italian Grand Prix'
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '55', '44', '1', '11', '23', '27', '14', '3', '20', '10', '31', '22', '18', '43', '77', '24']

                 field                                        Information
0         session_name                                         Qualifying
1           event_name                                 Italian Grand Prix
2  num_laps_in_results                                                 20
3      results_columns  [DriverNumber, BroadcastName, Abbreviation, Dr...
4            laps_head  {'Time': {0: 0 days 00:16:12.142000, 1: 0 days...

In [ ]:
import requests
import json
import pandas as pd

# Endpoint
url = "https://api.jolpi.ca/ergast/f1/2024/driverstandings/"

# Request
response = requests.get(url)


print("HTTP status code:", response.status_code)

data = json.loads(response.text)


driversstandings = data["MRData"]["StandingsTable"]["StandingsLists"][0]["DriverStandings"]

records = []
for driver in driversstandings:
    records.append({
        "name": driver["Driver"]["givenName"] + " " + driver["Driver"]["familyName"],
        "nationality": driver["Driver"]["nationality"],
        "points": int(driver["points"])
    })

df = pd.DataFrame(records)


print("Number of records returned:", len(df))

print(df.head(3))

df

HTTP status code: 200
Number of records returned: 24
              name nationality  points
0   Max Verstappen       Dutch     437
1     Lando Norris     British     374
2  Charles Leclerc  Monegasque     356

                name    nationality  points
0     Max Verstappen          Dutch     437
1       Lando Norris        British     374
2    Charles Leclerc     Monegasque     356
3      Oscar Piastri     Australian     292
4       Carlos Sainz        Spanish     290
5     George Russell        British     245
6     Lewis Hamilton        British     223
7       Sergio Pérez        Mexican     152
8    Fernando Alonso        Spanish      70
9       Pierre Gasly         French      42
10   Nico Hülkenberg         German      41
11      Yuki Tsunoda       Japanese      30
12      Lance Stroll       Canadian      24
13      Esteban Ocon         French      23
14   Kevin Magnussen         Danish      16
15   Alexander Albon           Thai      12
16  Daniel Ricciardo     Australian      12
17    Oliver Bearman        British       7
18  Franco Colapinto      Argentine       5
19       Guanyu Zhou        Chinese       4
20       Liam Lawson  New Zealander       4
21   Valtteri Bottas        Finnish       0
22    Logan Sargeant       American       0
23       Jack Doohan     Australian       0